language: node_js
node_js:
  - "node"

install:
  - npm install
script:
  - npm run build

before_deploy:
  - mkdir -p .theme
  - cp dist/templates.*.js .theme/
  - cp dist/styles.*.min.css .theme/

deploy:
  - provider: s3
    access_key_id: $AWS_S3_ACCESS_KEY
    secret_access_key: $AWS_S3_SECRET_KEY
    skip_cleanup: true
    local_dir: .theme
    bucket: wsb-integrations
    upload-dir: themes
    region: eu-central-1

